/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ververica.flink.training.examples;

import com.ververica.flink.training.common.FlinkClusterUtils;
import com.ververica.flink.training.common.ShoppingCartSource;
import org.apache.flink.api.common.eventtime.WatermarkStrategy;
import org.apache.flink.api.java.utils.ParameterTool;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.streaming.api.functions.sink.PrintSink;
import org.apache.flink.streaming.api.functions.sink.v2.DiscardingSink;

/**
 * Job that runs our example workflow, with some CLI parameter support
 *  --discard will discard records, instead of printing them to stdOut
 *  --numrecords <count> will stop the workflow after processing <count> records
 *  --parallelism <n> will set the cluster's slots to <n>, and thus the job parallelism
 */
public class BootcampExampleJob {

    public static void main(String[] args) throws Exception {
        ParameterTool parameters = ParameterTool.fromArgs(args);
        final StreamExecutionEnvironment env = FlinkClusterUtils.createConfiguredLocalEnvironment(parameters);
        env.getConfig().disableAutoGeneratedUIDs();

        final boolean discarding = parameters.has("discard");
        final long numRecords = parameters.getLong("numrecords", 1_000_000);

        new BootcampExampleWorkflow()
                .setCartStream(env.fromSource(new ShoppingCartSource(numRecords),
                                WatermarkStrategy.noWatermarks(),
                                "Shopping Cart Stream").uid("Shopping cart source"))
                .setResultSink(discarding ? new DiscardingSink<>() : new PrintSink<>())
                .build();

        env.execute("BootcampExampleJob");
    }
}